/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as CancelamentosRouteImport } from './routes/cancelamentos'
import { Route as ComoComprarRouteImport } from './routes/como-comprar'
import { Route as FaleConoscoRouteImport } from './routes/fale-conosco'
import { Route as FormasDePagamentoRouteImport } from './routes/formas-de-pagamento'
import { Route as PerguntasFrequentesRouteImport } from './routes/perguntas-frequentes'
import { Route as PoliticaDePrivacidadeRouteImport } from './routes/politica-de-privacidade'
import { Route as PrazoDeEntregaRouteImport } from './routes/prazo-de-entrega'
import { Route as RastreamentoRouteImport } from './routes/rastreamento'
import { Route as SobreNosRouteImport } from './routes/sobre-nos'
import { Route as TrocasEDevolucoesRouteImport } from './routes/trocas-e-devolucoes'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as CategoriaSlugRouteImport } from './routes/categoria.$slug'
import { Route as AdminAdminConfiguracoesRouteImport } from './routes/_admin.admin.configuracoes'
import { Route as AdminAdminDashboardRouteImport } from './routes/_admin.admin.dashboard'
import { Route as AdminAdminEstoqueRouteImport } from './routes/_admin.admin.estoque'
import { Route as AdminAdminProdutosRouteImport } from './routes/_admin.admin.produtos'
import { Route as AdminAdminVendasRouteImport } from './routes/_admin.admin.vendas'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CancelamentosRoute = CancelamentosRouteImport.update({
  id: '/cancelamentos',
  path: '/cancelamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const ComoComprarRoute = ComoComprarRouteImport.update({
  id: '/como-comprar',
  path: '/como-comprar',
  getParentRoute: () => rootRouteImport,
} as any)
const FaleConoscoRoute = FaleConoscoRouteImport.update({
  id: '/fale-conosco',
  path: '/fale-conosco',
  getParentRoute: () => rootRouteImport,
} as any)
const FormasDePagamentoRoute = FormasDePagamentoRouteImport.update({
  id: '/formas-de-pagamento',
  path: '/formas-de-pagamento',
  getParentRoute: () => rootRouteImport,
} as any)
const PerguntasFrequentesRoute = PerguntasFrequentesRouteImport.update({
  id: '/perguntas-frequentes',
  path: '/perguntas-frequentes',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDePrivacidadeRoute = PoliticaDePrivacidadeRouteImport.update({
  id: '/politica-de-privacidade',
  path: '/politica-de-privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const PrazoDeEntregaRoute = PrazoDeEntregaRouteImport.update({
  id: '/prazo-de-entrega',
  path: '/prazo-de-entrega',
  getParentRoute: () => rootRouteImport,
} as any)
const RastreamentoRoute = RastreamentoRouteImport.update({
  id: '/rastreamento',
  path: '/rastreamento',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreNosRoute = SobreNosRouteImport.update({
  id: '/sobre-nos',
  path: '/sobre-nos',
  getParentRoute: () => rootRouteImport,
} as any)
const TrocasEDevolucoesRoute = TrocasEDevolucoesRouteImport.update({
  id: '/trocas-e-devolucoes',
  path: '/trocas-e-devolucoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriaSlugRoute = CategoriaSlugRouteImport.update({
  id: '/categoria/$slug',
  path: '/categoria/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdminConfiguracoesRoute = AdminAdminConfiguracoesRouteImport.update({
  id: '/admin/configuracoes',
  path: '/admin/configuracoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminDashboardRoute = AdminAdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminEstoqueRoute = AdminAdminEstoqueRouteImport.update({
  id: '/admin/estoque',
  path: '/admin/estoque',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminProdutosRoute = AdminAdminProdutosRouteImport.update({
  id: '/admin/produtos',
  path: '/admin/produtos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminVendasRoute = AdminAdminVendasRouteImport.update({
  id: '/admin/vendas',
  path: '/admin/vendas',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cancelamentos': typeof CancelamentosRoute
  '/como-comprar': typeof ComoComprarRoute
  '/fale-conosco': typeof FaleConoscoRoute
  '/formas-de-pagamento': typeof FormasDePagamentoRoute
  '/perguntas-frequentes': typeof PerguntasFrequentesRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/prazo-de-entrega': typeof PrazoDeEntregaRoute
  '/rastreamento': typeof RastreamentoRoute
  '/sobre-nos': typeof SobreNosRoute
  '/trocas-e-devolucoes': typeof TrocasEDevolucoesRoute
  '/admin/login': typeof AdminLoginRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/admin/configuracoes': typeof AdminAdminConfiguracoesRoute
  '/admin/dashboard': typeof AdminAdminDashboardRoute
  '/admin/estoque': typeof AdminAdminEstoqueRoute
  '/admin/produtos': typeof AdminAdminProdutosRoute
  '/admin/vendas': typeof AdminAdminVendasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cancelamentos': typeof CancelamentosRoute
  '/como-comprar': typeof ComoComprarRoute
  '/fale-conosco': typeof FaleConoscoRoute
  '/formas-de-pagamento': typeof FormasDePagamentoRoute
  '/perguntas-frequentes': typeof PerguntasFrequentesRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/prazo-de-entrega': typeof PrazoDeEntregaRoute
  '/rastreamento': typeof RastreamentoRoute
  '/sobre-nos': typeof SobreNosRoute
  '/trocas-e-devolucoes': typeof TrocasEDevolucoesRoute
  '/admin/login': typeof AdminLoginRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/admin/configuracoes': typeof AdminAdminConfiguracoesRoute
  '/admin/dashboard': typeof AdminAdminDashboardRoute
  '/admin/estoque': typeof AdminAdminEstoqueRoute
  '/admin/produtos': typeof AdminAdminProdutosRoute
  '/admin/vendas': typeof AdminAdminVendasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/cancelamentos': typeof CancelamentosRoute
  '/como-comprar': typeof ComoComprarRoute
  '/fale-conosco': typeof FaleConoscoRoute
  '/formas-de-pagamento': typeof FormasDePagamentoRoute
  '/perguntas-frequentes': typeof PerguntasFrequentesRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/prazo-de-entrega': typeof PrazoDeEntregaRoute
  '/rastreamento': typeof RastreamentoRoute
  '/sobre-nos': typeof SobreNosRoute
  '/trocas-e-devolucoes': typeof TrocasEDevolucoesRoute
  '/admin/login': typeof AdminLoginRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/_admin/admin/configuracoes': typeof AdminAdminConfiguracoesRoute
  '/_admin/admin/dashboard': typeof AdminAdminDashboardRoute
  '/_admin/admin/estoque': typeof AdminAdminEstoqueRoute
  '/_admin/admin/produtos': typeof AdminAdminProdutosRoute
  '/_admin/admin/vendas': typeof AdminAdminVendasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cancelamentos'
    | '/como-comprar'
    | '/fale-conosco'
    | '/formas-de-pagamento'
    | '/perguntas-frequentes'
    | '/politica-de-privacidade'
    | '/prazo-de-entrega'
    | '/rastreamento'
    | '/sobre-nos'
    | '/trocas-e-devolucoes'
    | '/admin/login'
    | '/categoria/$slug'
    | '/admin/configuracoes'
    | '/admin/dashboard'
    | '/admin/estoque'
    | '/admin/produtos'
    | '/admin/vendas'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cancelamentos'
    | '/como-comprar'
    | '/fale-conosco'
    | '/formas-de-pagamento'
    | '/perguntas-frequentes'
    | '/politica-de-privacidade'
    | '/prazo-de-entrega'
    | '/rastreamento'
    | '/sobre-nos'
    | '/trocas-e-devolucoes'
    | '/admin/login'
    | '/categoria/$slug'
    | '/admin/configuracoes'
    | '/admin/dashboard'
    | '/admin/estoque'
    | '/admin/produtos'
    | '/admin/vendas'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/cancelamentos'
    | '/como-comprar'
    | '/fale-conosco'
    | '/formas-de-pagamento'
    | '/perguntas-frequentes'
    | '/politica-de-privacidade'
    | '/prazo-de-entrega'
    | '/rastreamento'
    | '/sobre-nos'
    | '/trocas-e-devolucoes'
    | '/admin/login'
    | '/categoria/$slug'
    | '/_admin/admin/configuracoes'
    | '/_admin/admin/dashboard'
    | '/_admin/admin/estoque'
    | '/_admin/admin/produtos'
    | '/_admin/admin/vendas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CancelamentosRoute: typeof CancelamentosRoute
  ComoComprarRoute: typeof ComoComprarRoute
  FaleConoscoRoute: typeof FaleConoscoRoute
  FormasDePagamentoRoute: typeof FormasDePagamentoRoute
  PerguntasFrequentesRoute: typeof PerguntasFrequentesRoute
  PoliticaDePrivacidadeRoute: typeof PoliticaDePrivacidadeRoute
  PrazoDeEntregaRoute: typeof PrazoDeEntregaRoute
  RastreamentoRoute: typeof RastreamentoRoute
  SobreNosRoute: typeof SobreNosRoute
  TrocasEDevolucoesRoute: typeof TrocasEDevolucoesRoute
  AdminLoginRoute: typeof AdminLoginRoute
  CategoriaSlugRoute: typeof CategoriaSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cancelamentos': {
      id: '/cancelamentos'
      path: '/cancelamentos'
      fullPath: '/cancelamentos'
      preLoaderRoute: typeof CancelamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/como-comprar': {
      id: '/como-comprar'
      path: '/como-comprar'
      fullPath: '/como-comprar'
      preLoaderRoute: typeof ComoComprarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fale-conosco': {
      id: '/fale-conosco'
      path: '/fale-conosco'
      fullPath: '/fale-conosco'
      preLoaderRoute: typeof FaleConoscoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/formas-de-pagamento': {
      id: '/formas-de-pagamento'
      path: '/formas-de-pagamento'
      fullPath: '/formas-de-pagamento'
      preLoaderRoute: typeof FormasDePagamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perguntas-frequentes': {
      id: '/perguntas-frequentes'
      path: '/perguntas-frequentes'
      fullPath: '/perguntas-frequentes'
      preLoaderRoute: typeof PerguntasFrequentesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-privacidade': {
      id: '/politica-de-privacidade'
      path: '/politica-de-privacidade'
      fullPath: '/politica-de-privacidade'
      preLoaderRoute: typeof PoliticaDePrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prazo-de-entrega': {
      id: '/prazo-de-entrega'
      path: '/prazo-de-entrega'
      fullPath: '/prazo-de-entrega'
      preLoaderRoute: typeof PrazoDeEntregaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rastreamento': {
      id: '/rastreamento'
      path: '/rastreamento'
      fullPath: '/rastreamento'
      preLoaderRoute: typeof RastreamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre-nos': {
      id: '/sobre-nos'
      path: '/sobre-nos'
      fullPath: '/sobre-nos'
      preLoaderRoute: typeof SobreNosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trocas-e-devolucoes': {
      id: '/trocas-e-devolucoes'
      path: '/trocas-e-devolucoes'
      fullPath: '/trocas-e-devolucoes'
      preLoaderRoute: typeof TrocasEDevolucoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categoria/$slug': {
      id: '/categoria/$slug'
      path: '/categoria/$slug'
      fullPath: '/categoria/$slug'
      preLoaderRoute: typeof CategoriaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/admin/configuracoes': {
      id: '/_admin/admin/configuracoes'
      path: '/admin/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AdminAdminConfiguracoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/dashboard': {
      id: '/_admin/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminAdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/estoque': {
      id: '/_admin/admin/estoque'
      path: '/admin/estoque'
      fullPath: '/admin/estoque'
      preLoaderRoute: typeof AdminAdminEstoqueRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/produtos': {
      id: '/_admin/admin/produtos'
      path: '/admin/produtos'
      fullPath: '/admin/produtos'
      preLoaderRoute: typeof AdminAdminProdutosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/vendas': {
      id: '/_admin/admin/vendas'
      path: '/admin/vendas'
      fullPath: '/admin/vendas'
      preLoaderRoute: typeof AdminAdminVendasRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAdminConfiguracoesRoute: typeof AdminAdminConfiguracoesRoute
  AdminAdminDashboardRoute: typeof AdminAdminDashboardRoute
  AdminAdminEstoqueRoute: typeof AdminAdminEstoqueRoute
  AdminAdminProdutosRoute: typeof AdminAdminProdutosRoute
  AdminAdminVendasRoute: typeof AdminAdminVendasRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminConfiguracoesRoute: AdminAdminConfiguracoesRoute,
  AdminAdminDashboardRoute: AdminAdminDashboardRoute,
  AdminAdminEstoqueRoute: AdminAdminEstoqueRoute,
  AdminAdminProdutosRoute: AdminAdminProdutosRoute,
  AdminAdminVendasRoute: AdminAdminVendasRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CancelamentosRoute: CancelamentosRoute,
  ComoComprarRoute: ComoComprarRoute,
  FaleConoscoRoute: FaleConoscoRoute,
  FormasDePagamentoRoute: FormasDePagamentoRoute,
  PerguntasFrequentesRoute: PerguntasFrequentesRoute,
  PoliticaDePrivacidadeRoute: PoliticaDePrivacidadeRoute,
  PrazoDeEntregaRoute: PrazoDeEntregaRoute,
  RastreamentoRoute: RastreamentoRoute,
  SobreNosRoute: SobreNosRoute,
  TrocasEDevolucoesRoute: TrocasEDevolucoesRoute,
  AdminLoginRoute: AdminLoginRoute,
  CategoriaSlugRoute: CategoriaSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
